<?php

/**
 *          ****************************************************************************************
 *          ****************|| PLATAFORMA SOLICITADA POR EQUIPO DE RECLUTAMIENTO  ||****************
 *          ****************************************************************************************
 * 
 *          @date               2020-02-10
 *          @author             Frank Montagne <frank@burtonservers.com>
 *          @copyright          2019-2020 Burton Technology https://burtonservers.com
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Simple lightweight panel to display skills required for the Profile they are looking for.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */

//  DEBUG EN PANTALLA   ///
/* error_reporting(E_ALL);
ini_set('display_errors', 1); */

//  HABILITAMOS EL ACCESO PUBLICO PARA REALIZAR LLAMADAS AJAX DESDE DOMINIOS PUBLICOS   /
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Auth-Token');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS');
header('Content-type: application/javascript; charset=utf-8');

//   RESCATAMOS TODO EL OUTPUT  //
/**  PARA IMPRIMIRLO EN JSON
 * $output = ob_get_contents(); ob_end_clean();
 */
ob_start();


date_default_timezone_set('America/Guayaquil');
require 'assets/scripts/utils.php';
//require 'assets/scripts/conn.php'; // PRODUCTION
require 'assets/scripts/c.php'; // DEVELOPING

$json = array();

if ($_POST || $_GET) {
    if ($_POST['meth']) {
        $method =    broom('reg', $_POST['meth']);
    }
    if ($_GET['meth']) {
        $method = broom('reg', $_GET['meth']);
    }

    //       BUILDER           //
    if ($method == 'construct') {

        $getJuice = file_get_contents('assets/scripts/juice.php');
        $getStyle = file_get_contents('assets/scripts/styles.php');
        $video = getBGVideo();

        $json['scriptResp'] = "done";
        $json['video'] = $video;
        $json['juice'] = $getJuice;
        $json['styles'] = $getStyle;
        $json['todaydate'] = date('Y-m-d');;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          GESTIONAR EL PANEL A MOSTRAR            //
    if ($method == 'loadPanel') {
        $panel = broom('reg', $_POST["panel"]);
        $user = broom('reg', $_POST["user"]);

        if ($panel == 'undefined') {
            $panelView = file_get_contents('modules/ads/view.php');
            $panelcontrol = file_get_contents('modules/ads/controller.php');

            $json['scriptResp'] = "loaded";
            $json['panel'] = $panelView;
            $json['control'] = $panelcontrol;
            $json['panelName'] = $panel;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $panelView = file_get_contents('modules/' . $panel . '/view.php');
        $panelcontrol = file_get_contents('modules/' . $panel . '/controller.php');
        $select = "UPDATE users SET panelUser = '" . $panel . "' WHERE id = '" . $user . "'";
        $result = $c->query($select);

        $json['scriptResp'] = "loaded";
        $json['panel'] = $panelView;
        $json['control'] = $panelcontrol;
        $json['panelName'] = $panel;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          USUARIO INICIA SESION           //
    if ($method == 'login') {

        $username = $_POST["username"];
        $password = $_POST['password'];
        $apiuri = $_POST['apiuri'];

        ////            CONSULTAMOS EL USUARIO EN LA BASE DE DATOS A VER SI EXISTE              ////
        if (filter_var($username, FILTER_VALIDATE_EMAIL)) {

            $query = " SELECT * "
                . "FROM users "
                . "WHERE email = '" . $username . "' AND statusUser = '1' LIMIT 1 ";
            $result = $c->query($query);
            if (!$result) {
                $json['scriptResp'] = "userqueryFail";
                $json['q'] = $query;
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            }
            $rows = $result->num_rows;
            $row = $result->fetch_array(MYSQLI_ASSOC);

            ////          RETORNAMOS UN JSON AL AJAX PARA ALIMENTAR EL JAVASCRIPT          ////
            if (password_verify($password, $row['password'])) {
                //   VERIFICAMOS SI TIENE IMAGEN CARGADA || CARGAMOS IMAGEN PREDETERMINADA        //
                $isavatar = "assets/img/users/" . $row["id"] . ".jpg";
                if (file_exists($isavatar)) {
                    $row['userImg'] = $apiuri . $isavatar;
                } else {
                    $isavatar2 = "assets/img/users/" . $row["id"] . ".png";
                    if (file_exists($isavatar2)) {
                        $row['userImg'] = $apiuri . $isavatar2;
                    } else {
                        $row['userImg'] = $apiuri . "assets/img/users/default.jpg";
                    }
                }
                $row['panelView'] = file_get_contents('modules/' . $row["panelUser"] . '/view.php');
                $row['login'] = "YES";

                $val_update = "UPDATE users SET lastLogin = '" . date('Y-m-d H:i:s') . "' WHERE id = '" . $row["id"] . "';";
                $val_result = $c->query($val_update) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $val_update . "'}");

                unset($row['password']);
                $json['userIntel'] = $row;
                $json['scriptResp'] = "match";
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            } else {
                $json['scriptResp'] = "noMatch";
                $json['q'] = $query;
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            }
        }
    }

    //          RETORNAR EL MENU LATERAL AUTORIZADO PARA EL USUARIO            //
    if ($method == 'showSideBar') {
        $user = $_POST["user"];
        $view = $_POST["view"];


        $viewSidebar = '
            <div class="page-sidebar mCustomScrollbar _mCS_1 mCS-autoHide  scroll" id="sidebarLoaded" data-useridpanel="' . $user . '">
                <ul class="x-navigation" id="barralateral">
                    <li class="xn-logo changePanel" data-panel="homeLogo">
                        <a href="#">___APPNAME___</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile ">
                        <a href="#" class="profile-mini fotoPerfil">
                            <img src="___PATHTOPROFILEPIC___" alt="User"/>
                        </a>
                        <div class="profile userPanelBG">
                            <div class="profile-image fotoPerfil">
                                <img src="___PATHTOPROFILEPIC___" alt="User"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name">
                                    ___NOMBRESUSUARIO___
                                    <div class="profile-data-title">
                                        ___ROLUSUARIO___
                                    </div>
                                </div>
                                <div class="profile-data-title nombreEstablecimiento">                        
                                    ___EMAILUSER___
                                </div>
                            </div>
                            <div class="profile-controls">
                                <!--                    
                                <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span></a>
                                <a href="pages-messages.html" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                                -->
                            </div>
                        </div>                                                                        
                    </li>
                    <li class="xn-title">Menú principal</li>
                    <li class="ads menuItem changePanel" data-panel="ads"><a href="#"><i class="fas fa-sort-amount-up"></i><span class="xn-text"> Ventas</span></a></li> 
                </ul>
            </div>
        ';

        $viewStatusb = '   
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><i class="fas fa-indent"></i></a>
                    </li>
                    <li class="xn-icon-button pull-right last">
                        <a href="#"><span class="fa fa-power-off"></span></a>
                        <ul class="xn-drop-left animated zoomIn">
                            <li><a href="#" class="mb-control" data-box="#mb-signout"><i class="fas fa-plug"></i> Salir</a></li>
                        </ul>                        
                    </li> 
                </ul>
            ';

        $json['scriptResp'] = "loaded";
        $json['sideb'] = $viewSidebar;
        $json['statusb'] = $viewStatusb;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          RESCATAMOS LOS DATOS DE LAS VENTAS        //
    if ($method == 'feedVentasTable') {

        // TOTAL DE VENTAS //
        $c->set_charset("utf8");
        $select = " SELECT *
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0' ";
        $result = $c->query($select);
        $rowsPro = 0;
        $rows = $result->num_rows;
        $regs = '';
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {

            $regs .= "             
            <tr>
                <td><strong class=\"idVentaCont\">" . $row['idVenta'] . "</strong></td>
                <td><strong>" . $row['dateVenta'] . "</strong></td>
                <td><span class=\"btn btn-blu\">" . $row['nombrePerfil'] . "</span></td>
                <td> <span class=\"btn btn-purple\">" . number_format($row['montoVenta'], 2, ',', '.') . " $</span> </td>
                <td> <span class=\"btn btn-danger deleteThisBtn\"><i class=\"fas fa-trash-alt\"></i></span> </td>
            </tr>
            ";
            $rowsPro++;
        }
        if ($rows == 0) {
            $regs = "             
            <tr>
                <td><strong></strong></td>
                <td><strong>Sin Registros</strong></td>
                <td></td>
                <td></td>
            </tr>
            ";
        }

        /** RECORREMOS TODAS LAS REGLAS PARA LISTAR LAS COMISIONES */
        $select = " SELECT *
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    ORDER BY dateVenta ASC";
        $result = $c->query($select);
        $rows = $result->num_rows;
        $regsComi = '';
        $regis = [];
        $months = [];
        while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
            $regis[] = $row;
            $regsComi .= implode(' | ', $row);
            $months[] = substr($row['dateVenta'], 5, 2);

            /** COMISIONES 3% N1 */
            $regsComi .= "             
                            <tr>
                                <td><strong class=\"idVentaContcomi\">" . $row['idVenta'] . "</strong></td>
                                <td><strong class=\"montoCont\">" . number_format($row['montoVenta'], 2, ',', '.') . "</strong></td>
                                <td><strong class=\"vendedorCont\">" . $row['nombrePerfil'] . "</strong></td>
                                <td><strong class=\"tipoVenCont\">Nivel1 (3%)</strong></td>
                                <td> <span class=\"btn btn-pink\">" . number_format(($row['montoVenta'] * 0.03), 2, ',', '.') . " $</span> </td>
                            </tr>
                        ";

            /** COMISIONES 1.2% N2 */
            $selectn2 = " SELECT * FROM `egcm`.`perfiles` WHERE `idPerfil` = '" . $row['parentPerfil'] . "' ";
            $resultn2 = $c->query($selectn2);
            $rowParentn2 = $resultn2->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION1 DE VENTA PROPIA > $5,000 */
            $selectr1 = " SELECT SUM(montoVenta) r1
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND idPerfil = '" . $rowParentn2['idPerfil'] . "'";
            $resultr1 = $c->query($selectr1);
            $rowParentr1 = $resultr1->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION2 DE venta del equipo > $35,000 */
            $selectr2 = " SELECT SUM(montoVenta) r2
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND parentPerfil = '" . $rowParentn2['idPerfil'] . "'";
            $resultr2 = $c->query($selectr2);
            $rowParentr2 = $resultr2->fetch_array(MYSQLI_ASSOC);
            $totalEquipoN2 = $rowParentr2['r2'];
            
            /** SI TODO CUMPLE AGREGAMOS LA COMISION */
            if ($rowParentr1['r1'] > 5000 && $totalEquipoN2 > 35000) {
                $regsComi .= "             
                            <tr>
                                <td><strong class=\"idVentaContcomi\">" . $row['idVenta'] . "</strong></td>
                                <td><strong class=\"montoCont\">" . number_format($row['montoVenta'], 2, ',', '.') . "</strong></td>
                                <td><strong class=\"vendedorCont\">" . $rowParentn2['nombrePerfil'] . "</strong></td>
                                <td><strong class=\"tipoVenCont\">Nivel2 (1.2%)</strong></td>
                                <td> <span class=\"btn btn-pink\">" . number_format(($row['montoVenta'] * 0.012), 2, ',', '.') . " $</span> </td>
                            </tr>
                        ";
            }

            /** COMISIONES 0.12% N3 */
            $selectn3 = " SELECT * FROM `egcm`.`perfiles` WHERE `idPerfil` = '" . $rowParentn2['parentPerfil'] . "' ";
            $resultn3 = $c->query($selectn3);
            $rowParentn3 = $resultn3->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION1 DE VENTA PROPIA > $8,000 */
            $selectr1 = " SELECT SUM(montoVenta) r1
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND idPerfil = '" . $rowParentn3['idPerfil'] . "'";
            $resultr1 = $c->query($selectr1);
            $rowParentr1 = $resultr1->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION2 DE venta del equipo > $60,000 */
            $selectr2 = " SELECT SUM(montoVenta) r2
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND parentPerfil = '" . $rowParentn3['idPerfil'] . "'";
            $resultr2 = $c->query($selectr2);
            $rowParentr2 = $resultr2->fetch_array(MYSQLI_ASSOC);
            $totalEquipoN3 = $rowParentr2['r2'];
            
            /** SI TODO CUMPLE AGREGAMOS LA COMISION */
            if ($rowParentr1['r1'] > 8000 && ($totalEquipoN2 + $totalEquipoN3)  > 60000) {
                $regsComi .= "             
                            <tr>
                                <td><strong class=\"idVentaContcomi\">" . $row['idVenta'] . "</strong></td>
                                <td><strong class=\"montoCont\">" . number_format($row['montoVenta'], 2, ',', '.') . "</strong></td>
                                <td><strong class=\"vendedorCont\">" . $rowParentn3['nombrePerfil'] . "</strong></td>
                                <td><strong class=\"tipoVenCont\">Nivel3 (0.12%)</strong></td>
                                <td> <span class=\"btn btn-pink\">" . number_format(($row['montoVenta'] * 0.0012), 2, ',', '.') . " $</span> </td>
                            </tr>
                        ";
            }

            /** COMISIONES 0.08% N4 */
            $selectn4 = " SELECT * FROM `egcm`.`perfiles` WHERE `idPerfil` = '" . $rowParentn3['parentPerfil'] . "' ";
            $resultn4 = $c->query($selectn4);
            $rowParentn4 = $resultn4->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION1 DE VENTA PROPIA > $8,000 */
            $selectr1 = " SELECT SUM(montoVenta) r1
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND idPerfil = '" . $rowParentn4['idPerfil'] . "'";
            $resultr1 = $c->query($selectr1);
            $rowParentr1 = $resultr1->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION2 DE venta del equipo > $120,000 */
            $selectr2 = " SELECT SUM(montoVenta) r2
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND parentPerfil = '" . $rowParentn4['idPerfil'] . "'";
            $resultr2 = $c->query($selectr2);
            $rowParentr2 = $resultr2->fetch_array(MYSQLI_ASSOC);
            $totalEquipoN4 = $rowParentr2['r2'];
            
            /** SI TODO CUMPLE AGREGAMOS LA COMISION */
            if ($rowParentr1['r1'] > 8000 && ($totalEquipoN2 + $totalEquipoN3 + $totalEquipoN4)  > 120000) {
                $regsComi .= "             
                            <tr>
                                <td><strong class=\"idVentaContcomi\">" . $row['idVenta'] . "</strong></td>
                                <td><strong class=\"montoCont\">" . number_format($row['montoVenta'], 2, ',', '.') . "</strong></td>
                                <td><strong class=\"vendedorCont\">" . $rowParentn4['nombrePerfil'] . "</strong></td>
                                <td><strong class=\"tipoVenCont\">Nivel4 (0.08%)</strong></td>
                                <td> <span class=\"btn btn-pink\">" . number_format(($row['montoVenta'] * 0.0008), 2, ',', '.') . " $</span> </td>
                            </tr>
                        ";
            }

            /** COMISIONES 0.06% N5 */
            $selectn5 = " SELECT * FROM `egcm`.`perfiles` WHERE `idPerfil` = '" . $rowParentn4['parentPerfil'] . "' ";
            $resultn5 = $c->query($selectn5);
            $rowParentn5 = $resultn5->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION1 DE VENTA PROPIA > $6,000 */
            $selectr1 = " SELECT SUM(montoVenta) r1
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND idPerfil = '" . $rowParentn5['idPerfil'] . "'";
            $resultr1 = $c->query($selectr1);
            $rowParentr1 = $resultr1->fetch_array(MYSQLI_ASSOC);

            /** RESTRICCION2 DE venta del equipo > $240,000 */
            $selectr2 = " SELECT SUM(montoVenta) r2
                    FROM `ventas` ven
                    LEFT JOIN perfiles per ON (ven.vendedorVenta = per.idPerfil)
                    WHERE deletedVenta = '0'
                    AND parentPerfil = '" . $rowParentn5['idPerfil'] . "'";
            $resultr2 = $c->query($selectr2);
            $rowParentr2 = $resultr2->fetch_array(MYSQLI_ASSOC);
            $totalEquipoN5 = $rowParentr2['r2'];
            
            /** SI TODO CUMPLE AGREGAMOS LA COMISION */
            if ($rowParentr1['r1'] > 6000 && ($totalEquipoN2 + $totalEquipoN3 + $totalEquipoN4 + $totalEquipoN4)  > 240000) {
                $regsComi .= "             
                            <tr>
                                <td><strong class=\"idVentaContcomi\">" . $row['idVenta'] . "</strong></td>
                                <td><strong class=\"montoCont\">" . number_format($row['montoVenta'], 2, ',', '.') . "</strong></td>
                                <td><strong class=\"vendedorCont\">" . $rowParentn5['nombrePerfil'] . "</strong></td>
                                <td><strong class=\"tipoVenCont\">Nivel5 (0.06%)</strong></td>
                                <td> <span class=\"btn btn-pink\">" . number_format(($row['montoVenta'] * 0.0006), 2, ',', '.') . " $</span> </td>
                            </tr>
                        ";
            }
        }


        $json['scriptResp'] = "done";
        $json['regs'] = $regs;
        $json['regsComi'] = $regsComi;
        $json['rowsPro'] = $rowsPro;
        $json['months'] = $months;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          CREAR NUEVA VENTA        //
    if ($method == 'addnewVent') {

        $cliente  = $_POST['cliente'];
        $estatus  = '1';
        $vendedor  = str_replace("_", " ", $_POST['vendedor']);;
        $desc  = $_POST['desc'];
        $date  = $_POST['date'];
        $total  = $_POST['total'];

        $insertStr = "INSERT INTO ventas(nameVenta,statusVenta,descVenta,dateVenta,vendedorVenta,montoVenta,lasteditVenta) "
            . "VALUES  ('" . $cliente
            . "','" . $estatus
            . "','" . $desc
            . "','" . $date
            . "','" . $vendedor
            . "','" . $total
            . "','" . date("Y-m-d H:i:s") . "')";
        $resultIns = $c->query($insertStr);

        if ($resultIns) {
            $json['scriptResp'] = "done";
            $json['status'] = "added";
            $json['post'] = json_encode($_POST);
            $json['insertStr'] = $insertStr;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "done";
            $json['status'] = 'UPDATEERROR';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }
    
    //          ELIMINAR VENTA           //
    if ($method == 'deleteVenta') {

        $idVenta =    broom('num', $_POST['idVenta']);
        $val_select = "UPDATE ventas SET deletedVenta = '1', statusVenta = '0' WHERE idVenta = '" . $idVenta . "'";
        $val_result = $c->query($val_select);

        if ($val_result) {
            $json['scriptResp'] = "done";
            $json['val_select'] = $val_select;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "error";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }
}

//   Si no se llamó ningún método de la API     //
$output = ob_get_contents();
$json['post'] = json_encode($_POST);
$json['get'] = json_encode($_GET);
$json['files'] = json_encode($_FILES);
$json['msg'] = "Mute API";
$json['output'] = $output;
ob_end_clean();
echo json_encode($json);
return;
