<?php

/**
 *          ****************************************************************************
 *          **********************||  GO TRADE PANEL ADMINISTRATIVO ||******************
 *          ****************************************************************************
 * 
 *          @date               2019-11-15
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2019-2020 Burton Technology https://burtonservers.com
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Custom admin dashboard for easy lightweight SPA deployment.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */

/* * **** PURIFICAMOS VARIABLES ****** */

function broom($type, $string)
{
    if ($type == "reg") { /* FILTRAR a - Z Y ESPACIOS */
        return preg_replace("/[^ \w]+/", "", $string);
    }
    if ($type == "text") { /* FILTRAR SOLO TEXTO PARA LECTURA SIN CARCTERES ESPECIALES */
        return filter_var($string, FILTER_SANITIZE_STRING);
    }
    if ($type == "num") { /* FILTRAR TODO MENOS NUMEROS */
        return preg_replace('/\D/', '', $string);
    }
    if ($type == "spa") { /* CONVERTIR A ESPAñL */
        return preg_replace('#[^\p{L}\s-]#u', '', $string);
    }
    if ($type == "url") { /* TEXTO PARA URL */
        return str_replace('+', '_', urlencode(preg_replace("/[^ \w]+/", "", $string)));
    }
}

/** IMPORTAMOS EL DUMP DE LA DATABASE POR PHP (CUANDO EL HOSTING ES MUY LENTO ) */
function masterRestore($c)
{

    $filename = 'encuestas.sql';
    $templine = '';
    $lines = file($filename);
    foreach ($lines as $line) {
        if (substr($line, 0, 2) == '--' || $line == '')
            continue;

        $templine .= $line;
        if (substr(trim($line), -1, 1) == ';') {

            $result = $c->query($templine);
            if (!$result) {
                die('QUERY ERROR');
            }
            $templine = '';
        }
    }
    echo "Tables imported successfully";
}

/** EXPORTAMOS EL DUMP DE LA DATABASE POR PHP (CUANDO EL HOSTING ES MUY LENTO ) */
function masterBackup()
{
    // Construimos el nombre de archivo 
    $fecha = date("Ymd");
    $salida_sql = DB_DATABASE . $fecha . '.sql';

    //Comando para genera respaldo de MySQL, enviamos las variales de conexion y el destino
    $dump = "mysqldump -h" . DB_HOST . " -u" . DB_USER . " -p" . DB_PASSWORD . " --opt " . DB_DATABASE . " > $salida_sql 2>&1";
    echo $dump . '<br />';
    $output = exec($dump); //Ejecutamos el comando para respaldo de la DB

    echo 'Proceso terminado!' . '<br />';
    return;
}

/*
 * +++++++++++++++++++++++      VIDEO ALEATORIO DE BACKGROUND       +++++++++++++++++++++++
 */
function getBGVideo()
{
    $r = rand(1, 14);
    switch ($r) {
        case 1:
            $video = "wTeKnXaOmjg"; // CIRCUIT SPARKLIN 
            break;
        case 2:
            $video = "7hiLrRaC2Ps"; // CIRCUIT FLOW LIGHT
            break;
        case 3:
            $video = "bZpBOItNVwM"; // INK DROPS
            break;
        case 4:
            $video = "RCZPsCjAbEU"; // BLUE SPACE CLOUDS 
            break;
        case 5:
            $video = "volsw7nOvvk"; // BLUE PARTICLES
            break;
        case 6:
            $video = "IxFxsq-ANpY"; // Smoke Trail
            break;
        case 7:
            $video = "LcF6ut-1M94"; // IRESTORM
            break;
        case 8:
            $video = "KGlWaG4N4L8"; // GOLDNE SPARKS
            break;
        case 9:
            $video = "MoQEPx30KHQ"; // GOLDNE SPARKS FLOATING
            break;
        case 10:
            $video = "lJf9GdAEy-A"; // BLUE FALLING VECTORS
            break;
        case 11:
            $video = "1ghLEigenZM"; // ORANGE PARTICLES
            break;
        case 12:
            $video = "UWF7dZTLW4c"; // SWAMP
            break;
        case 13:
            $video = "iE4pMhb8wjc"; // RINGS
            break;
        case 14:
            $video = "wOouUV1m5Wo"; // BONFIRE
            break;
    }
    // $video = "volsw7nOvvk"; // STATIC VIDEO
    $code = '<div class="video-background">
                <div class="video-foreground">
                    <iframe src="https://www.youtube.com/embed/' . $video . '?controls=0&showinfo=0&rel=0&mute=1&modestbranding=1&autoplay=1&loop=1&playlist=' . $video . '" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="video-overlay"></div>
            </div>';
    return $code;
}

function getColorSeries()
{
    
    $lineArr = [];
    for ($i = 1; $i <= 20; $i++) {
        $r = rand(1, 20);
        switch ($r) {
            case 1:
                $color = "#fe6594"; //   
                break;
            case 2:
                $color = "#7b77c8"; //   
                break;
            case 3:
                $color = "#4cc3f8"; //  
                break;
            case 4:
                $color = "#feb794"; // 
                break;
            case 5:
                $color = "#8d5cff"; //  
                break;
            case 6:
                $color = "#ff5a5a"; //  
                break;
            case 7:
                $color = "#46ffdb"; // 
                break;
            case 8:
                $color = "#00b5e4"; // 
                break;
            case 9:
                $color = "#957afc"; // 
                break;
            case 10:
                $color = "#a43981"; // 
                break;
            case 11:
                $color = "#69deb5"; //  
                break;
            case 12:
                $color = "#ff918e"; // 
                break;
            case 13:
                $color = "#4c9fd9"; // 
                break;
            case 14:
                $color = "#f99fee"; // 
                break;
            case 15:
                $color = "#9482b3"; // 
                break;
            case 16:
                $color = "#fc74cf"; // 
                break;
            case 17:
                $color = "#8b71f5"; // 
                break;
            case 18:
                $color = "#d7478b"; // 
                break;
            case 19:
                $color = "#f9921b"; // 
                break;
            case 20:
                $color = "#6bc4ff"; // 
                break;
        }
        if (in_array($color, $lineArr)) {
            $i--;
        } else {
            $lineArr[] = $color;
        }
    }
    return $lineArr;
}

/** 
 * +++++++++++++++++++++++      GUARDAR VISITA DE USUARIO EN LA BASE DE DATOS       +++++++++++++++++++++++
 */
function trackvisitor($page)
{
    $tracking_page_name = $page;
    if (isset($_SERVER['HTTP_REFERER'])) {
        $ref = $_SERVER['HTTP_REFERER'];
    } else {
        $ref = "DIRECTO";
    }
    $agent = $_SERVER['HTTP_USER_AGENT'];
    $ip = $_SERVER['REMOTE_ADDR'];
    $host_name = gethostbyaddr($_SERVER['REMOTE_ADDR']);
    $query = "INSERT INTO gt_track(tm, ref, agent, ip, tracking_page_name, domain, ip_value)    VALUES('" . date('Y-m-d') . "','$ref','$agent','$ip','$tracking_page_name','$host_name','" . date('H:i:s') . "')";
    $track = mysqli_query($c, $query) or die("no inserto" . mysqli_error($c));
}

/**
 * +++++++++++++++++++++++      CUSTOM FILTERS       +++++++++++++++++++++++
 */
function sanitize($string)
{
    $string = str_replace(' ', '--', $string);
    $string = str_replace('.', '-DOT-', $string);
    $string = str_replace('@', '-AT-', $string);
    return preg_replace('/[^\p{L}0-9\-\.]/', '', $string);
}

$defaultPortalForm = '  
    <form name="leads_form" method="post" id="leadsForm">
        <input type="text" name="nombreCliente" placeholder="Nombre completo" id="nomreUser">
        <input type="text" name="telefonoCliente" placeholder="Telefono de contacto" id="telUser">
        <input type="text" name="emailCliente" placeholder="Correo electronico" id="emailUser">
        <div class="login-help">
            <ul class="list">
                <li class="list__item">
                    <label class="label--checkbox">
                        <input type="checkbox" class="checkbox" onchange="disableSubmit(!this.checked)">
                        <span> Acepto todos los <a target="_blank" rel="noopener" href="#"> términos y condiciones</a></span>
                    </label>
                </li>
            </ul>
        </div>
        <input type="submit" name="accept" class="login login-submit" value="Enviar" id="btnLogin" disabled>
        ___FBBTN___
    </form>';
